codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch:
      default: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - develop
    - main