version: "3"
services:
  claon_database:
    container_name: claon_db
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "claon_db"
      POSTGRES_USER: "colaon_user"
      POSTGRES_PASSWORD: "colaon_password"
  redis:
    image: redis:6.0.5
    container_name: claon_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
