server:
  port: 8080

spring:
  config:
    import: classpath:auth-config.yml, classpath:aws-config.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/claon_db
    username: colaon_user
    password: colaon_password

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true