server:
  port: 8080

spring:
  config:
    import: classpath:auth-config.yml, classpath:dev-database-config.yml, classpath:aws-config.yml, classpath:dev-redis-config.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true