server:
  port: 8000

spring:
  application:
    name: gateway
  security:
    user:
      name: claon
      password: 1234
  main:
    web-application-type: reactive

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
      management.context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: logs/gateway/info.log
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:auth-config.yml

  cloud:
    discovery:
      enabled: true
    loadbalancer:
      configurations: health-check
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthenticationHeaderFilter
        - id: center
          uri: lb://CENTER
          predicates:
            - Path=/center/**
          filters:
            - RewritePath=/center/(?<segment>.*), /$\{segment}
            - AuthenticationHeaderFilter
        - id: post
          uri: lb:POST
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/(?<segment>.*), /$\{segment}
            - AuthenticationHeaderFilter

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
