server:
  port: 8090

spring:
  application:
    name: monitor
  security:
    user:
      name: claon
      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: local

  boot:
    admin:
      ui:
        cache.no-cache: true
        cache-templates: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
