server:
  port: 8080

spring:
  application:
    name: auth
  security:
    user:
      name: claon
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
      management.context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: logs/auth/info.log
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:auth-config.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/claon_db
    username: colaon_user
    password: colaon_password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
