server:
  port: 8083

spring:
  application:
    name: post
  security:
    user:
      name: claon
      password: 1234

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
      management.context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: logs/post/info.log
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/claon_db
    username: colaon_user
    password: colaon_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
